# Generated by Django 3.1.7 on 2021-05-24 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('1', 'cartagena'), ('2', 'vancouver'), ('3', 'sanfrancisco'), ('4', 'losangeles')], max_length=240, unique=True)),
                ('months', models.CharField(choices=[('1', 'January'), ('2', 'Feb'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=240, unique=True)),
                ('budget', models.CharField(choices=[('1', 'low'), ('2', 'Medium'), ('3', 'High'), ('4', 'luxury')], max_length=240, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='loginapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='loginapp.user')),
                ('posted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_for', to='loginapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('1', 'cartagena'), ('2', 'vancouver'), ('3', 'sanfrancisco'), ('4', 'losangeles')], max_length=240, unique=True)),
                ('months', models.CharField(choices=[('1', 'January'), ('2', 'Feb'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=240, unique=True)),
                ('budget', models.CharField(choices=[('1', 'low'), ('2', 'Medium'), ('3', 'High'), ('4', 'luxury')], max_length=240, unique=True)),
                ('activity', models.CharField(choices=[('1', 'Budget Planning'), ('2', 'Attire'), ('3', 'Flowers'), ('4', 'Decor'), ('5', 'Music'), ('6', 'Photography'), ('7', 'Gifts'), ('8', 'Ceremony'), ('9', 'Stationary'), ('10', 'Wedding Rings'), ('11', 'Transportation'), ('12', 'Misc')], max_length=240, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='loginapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_comment', to='loginapp.message')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='loginapp.user')),
            ],
        ),
    ]
