# Generated by Django 3.1.7 on 2021-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20210524_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activity',
            field=models.CharField(choices=[('1', 'Budget Planning'), ('2', 'Attire'), ('3', 'Flowers'), ('4', 'Decor'), ('5', 'Music'), ('6', 'Photography'), ('7', 'Gifts'), ('8', 'Ceremony'), ('9', 'Stationary'), ('10', 'Wedding Rings'), ('11', 'Transportation'), ('12', 'Misc')], max_length=240),
        ),
        migrations.AlterField(
            model_name='customer',
            name='months',
            field=models.CharField(choices=[('1', 'January'), ('2', 'Feb'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=240),
        ),
    ]
