# Generated by Django 3.1.7 on 2021-05-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20210525_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='budget',
            field=models.CharField(choices=[('1', 'low'), ('2', 'Medium'), ('3', 'High'), ('4', 'luxury')], max_length=240),
        ),
        migrations.AlterField(
            model_name='customer',
            name='destination',
            field=models.CharField(choices=[('1', 'cartagena'), ('2', 'vancouver'), ('3', 'sanfrancisco'), ('4', 'losangeles')], max_length=240),
        ),
        migrations.AlterField(
            model_name='planner',
            name='budget',
            field=models.CharField(choices=[('1', 'low'), ('2', 'Medium'), ('3', 'High'), ('4', 'luxury')], max_length=240),
        ),
        migrations.AlterField(
            model_name='planner',
            name='destination',
            field=models.CharField(choices=[('1', 'cartagena'), ('2', 'vancouver'), ('3', 'sanfrancisco'), ('4', 'losangeles')], max_length=240),
        ),
        migrations.AlterField(
            model_name='planner',
            name='months',
            field=models.CharField(choices=[('1', 'January'), ('2', 'Feb'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=240),
        ),
    ]
