# Generated by Django 3.1.7 on 2021-05-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20210525_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activity',
            field=models.CharField(choices=[('Budget Planning', 'Budget Planning'), ('Attire', 'Attire'), ('Flowers', 'Flowers'), ('Decor', 'Decor'), ('Music', 'Music'), ('6', 'Photography'), ('7', 'Gifts'), ('8', 'Ceremony'), ('9', 'Stationary'), ('10', 'Wedding Rings'), ('11', 'Transportation'), ('12', 'Misc')], max_length=240),
        ),
    ]
