# Generated by Django 3.1.7 on 2021-05-26 15:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20210525_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activity',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Budget Planning'), ('2', 'Attire'), ('3', 'Flowers'), ('4', 'Decor'), ('5', 'Music'), ('6', 'Photography'), ('7', 'Gifts'), ('8', 'Ceremony'), ('9', 'Stationary'), ('10', 'Wedding Rings'), ('11', 'Transportation'), ('12', 'Misc')], max_length=240),
        ),
        migrations.AlterField(
            model_name='customer',
            name='budget',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'low'), ('2', 'Medium'), ('3', 'High'), ('4', 'luxury')], max_length=240),
        ),
        migrations.AlterField(
            model_name='customer',
            name='destination',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'cartagena'), ('2', 'vancouver'), ('3', 'sanfrancisco'), ('4', 'losangeles')], max_length=240),
        ),
        migrations.AlterField(
            model_name='customer',
            name='months',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'January'), ('2', 'Feb'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=240),
        ),
        migrations.AlterField(
            model_name='planner',
            name='budget',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'low'), ('2', 'Medium'), ('3', 'High'), ('4', 'luxury')], max_length=240),
        ),
        migrations.AlterField(
            model_name='planner',
            name='destination',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'cartagena'), ('2', 'vancouver'), ('3', 'sanfrancisco'), ('4', 'losangeles')], max_length=240),
        ),
        migrations.AlterField(
            model_name='planner',
            name='months',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'January'), ('2', 'Feb'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=240),
        ),
    ]
